# Generated by Django 5.1.4 on 2025-02-05 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_processedimage_processed_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processedimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='finger_name',
            field=models.CharField(blank=True, choices=[('left_thumb', 'Left Thumb'), ('left_four', 'Left Four Fingers'), ('right_thumb', 'Right Thumb'), ('right_four', 'Right Four Fingers')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
