# Generated by Django 5.1.5 on 2025-03-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_processedimage_options_note_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedimage',
            name='original_image',
        ),
        migrations.RemoveField(
            model_name='processedimage',
            name='processed_image',
        ),
        migrations.AddField(
            model_name='processedimage',
            name='finger_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processedimage',
            name='image_path',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processedimage',
            name='user_id',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
