# Generated by Django 5.1.4 on 2024-12-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_processedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
    ]
