# Generated by Django 5.1.5 on 2025-04-09 19:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_processedimage_original_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedimage',
            name='finger_name',
        ),
        migrations.RemoveField(
            model_name='processedimage',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='processedimage',
            name='user_id',
        ),
        migrations.AddField(
            model_name='processedimage',
            name='original_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_images', to='api.note'),
        ),
        migrations.AddField(
            model_name='processedimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
